# Generated by Django 6.0.7 on 2026-08-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pendiente'), ('ACTIVE', 'activo'), ('COMPLETED', 'completado'), ('CANCELLED', 'cancelado')], default='PENDING'),
        ),
    ]
